config/routes.rb
Wizardfuel::Application.routes.draw do
  resources :wizards

  root :to => 'wizards#index'

end

app/models/wizard.rb
class Wizard < ActiveRecord::Base
  attr_accessible :field1, :field2, :field3, :field4, :field5, :field6
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/wizards_controller.rb
class WizardsController < ApplicationController
  # GET /wizards
  # GET /wizards.json
  def index
    @wizards = Wizard.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wizards }
    end
  end

  # GET /wizards/1
  # GET /wizards/1.json
  def show
    @wizard = Wizard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wizard }
    end
  end

  # GET /wizards/new
  # GET /wizards/new.json
  def new
    @wizard = Wizard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wizard }
    end
  end

  # GET /wizards/1/edit
  def edit
    @wizard = Wizard.find(params[:id])
  end

  # POST /wizards
  # POST /wizards.json
  def create
    @wizard = Wizard.new(params[:wizard])

    respond_to do |format|
      if @wizard.save
        format.html { redirect_to @wizard, notice: 'Wizard was successfully created.' }
        format.json { render json: @wizard, status: :created, location: @wizard }
      else
        format.html { render action: "new" }
        format.json { render json: @wizard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wizards/1
  # PUT /wizards/1.json
  def update
    @wizard = Wizard.find(params[:id])

    respond_to do |format|
      if @wizard.update_attributes(params[:wizard])
        format.html { redirect_to @wizard, notice: 'Wizard was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @wizard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wizards/1
  # DELETE /wizards/1.json
  def destroy
    @wizard = Wizard.find(params[:id])
    @wizard.destroy

    respond_to do |format|
      format.html { redirect_to wizards_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wizards_helper.rb
module WizardsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wizardfuel</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
	<div class"container">
		<%= yield %>
	</div>

</body>
</html>

app/views/wizards/_form.html.erb
<%= simple_form_for(@wizard) do |f| %>

<div class="row-fluid">
  <div class="span2">
  </div>
  <div class="span8">
    <div>
      <div id="MyWizard" class="wizard">
        <ul class="steps">
          <li data-target="#step1" class="active"><span class="badge badge-info">1</span>Step 1<span class="chevron"></span></li>
          <li data-target="#step2"><span class="badge">2</span>Step 2<span class="chevron"></span></li>
          <li data-target="#step3"><span class="badge">3</span>Step 3<span class="chevron"></span></li>
          <li data-target="#step4"><span class="badge">4</span>Step 4<span class="chevron"></span></li>
          <li data-target="#step5"><span class="badge">5</span>Step 5<span class="chevron"></span></li>
        </ul>
      </div><br>
      <div class="step-content">
        <div class="step-pane active" id="step1">
          <div class="field">
            <%= f.input :field1 %><br />
          </div>
        </div>
        <div class="step-pane" id="step2">
          <div class="field">
            <%= f.input :field2 %><br />
          </div>
        </div>
        <div class="step-pane" id="step3">
          <div class="field">
            <%= f.input :field3 %><br />
          </div>
        </div>
        <div class="step-pane" id="step4">
          <div class="field">
            <%= f.input :field4 %><br />
          </div>
        </div>
        <div class="step-pane" id="step5">
          <div class="field">
            <%= f.input :field5 %><br />
          </div>
        </div>
        <div class="form-actions">
          <input type="button" class="btn btn" id="btnWizardPrev" value="prev">
          <input type="button" class="btn btn" id="btnWizardNext" value="next">
          <%= f.submit :class => 'btn btn-primary', :id => 'wizard-submit' %>
          <div class="pull-right">
            <%= link_to 'Cancel', wizards_path, :class => 'btn btn-danger' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% end %>

app/views/wizards/edit.html.erb
<h1>Editing wizard</h1>

<%= render 'form' %>

app/views/wizards/index.html.erb
<h1>Listing wizards</h1>

<table>
  <tr>
    <th>Field1</th>
    <th>Field2</th>
    <th>Field3</th>
    <th>Field4</th>
    <th>Field5</th>
    <th>Field6</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wizards.each do |wizard| %>
  <tr>
    <td><%= wizard.field1 %></td>
    <td><%= wizard.field2 %></td>
    <td><%= wizard.field3 %></td>
    <td><%= wizard.field4 %></td>
    <td><%= wizard.field5 %></td>
    <td><%= wizard.field6 %></td>
    <td><%= link_to 'Show', wizard %></td>
    <td><%= link_to 'Edit', edit_wizard_path(wizard) %></td>
    <td><%= link_to 'Destroy', wizard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wizard', new_wizard_path %>

app/views/wizards/new.html.erb
<h1>New wizard</h1>

<%= render 'form' %>

app/views/wizards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Field1:</b>
  <%= @wizard.field1 %>
</p>

<p>
  <b>Field2:</b>
  <%= @wizard.field2 %>
</p>

<p>
  <b>Field3:</b>
  <%= @wizard.field3 %>
</p>

<p>
  <b>Field4:</b>
  <%= @wizard.field4 %>
</p>

<p>
  <b>Field5:</b>
  <%= @wizard.field5 %>
</p>

<p>
  <b>Field6:</b>
  <%= @wizard.field6 %>
</p>


<%= link_to 'Edit', edit_wizard_path(@wizard) %> |
<%= link_to 'Back', wizards_path %>